"""Update flashcard model for task management

Revision ID: 71908232ca08
Revises: feaec81ee0a3
Create Date: 2024-12-27 18:43:10.116442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71908232ca08'
down_revision = 'feaec81ee0a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('time_required', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('question')
        batch_op.drop_column('answer')
        batch_op.drop_column('last_reviewed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_reviewed', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('answer', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('question', sa.TEXT(), nullable=False))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('completed')
        batch_op.drop_column('time_required')
        batch_op.drop_column('task_description')

    # ### end Alembic commands ###
