"""Added password column

Revision ID: e037844689c4
Revises: 
Create Date: 2024-12-24 19:20:46.898315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e037844689c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gems', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_focus_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('most_productive_day', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('total_focus_time', sa.Integer(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(length=200), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('total_focus_time')
        batch_op.drop_column('most_productive_day')
        batch_op.drop_column('last_focus_date')
        batch_op.drop_column('gems')
        batch_op.drop_column('streak')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
